export interface ModalityInfo {
    description: string;
    isRetired?: boolean;
}

export const DicomModalities: Record<string, ModalityInfo> = {
    'AR': { description: 'Autorefraction' },
    'AS': { description: 'Angioscopy', isRetired: true },
    'ASMT': { description: 'Content Assessment Results' },
    'AU': { description: 'Audio' },
    'BDUS': { description: 'Bone Densitometry (ultrasound)' },
    'BI': { description: 'Biomagnetic imaging' },
    'BMD': { description: 'Bone Densitometry (X-Ray)' },
    'CD': { description: 'Color flow Doppler', isRetired: true },
    'CF': { description: 'Cinefluorography', isRetired: true },
    'CP': { description: 'Colposcopy', isRetired: true },
    'CR': { description: 'Computed Radiography' },
    'CS': { description: 'Cystoscopy', isRetired: true },
    'CT': { description: 'Computed Tomography' },
    'DD': { description: 'Duplex Doppler', isRetired: true },
    'DF': { description: 'Digital fluoroscopy', isRetired: true },
    'DG': { description: 'Diaphanography' },
    'DM': { description: 'Digital microscopy', isRetired: true },
    'DOC': { description: 'Document' },
    'DS': { description: 'Digital Subtraction Angiography', isRetired: true },
    'DX': { description: 'Digital Radiography' },
    'EC': { description: 'Echocardiography', isRetired: true },
    'ECG': { description: 'Electrocardiography' },
    'EPS': { description: 'Cardiac Electrophysiology' },
    'ES': { description: 'Endoscopy' },
    'FA': { description: 'Fluorescein angiography', isRetired: true },
    'FID': { description: 'Fiducials' },
    'FS': { description: 'Fundoscopy', isRetired: true },
    'GM': { description: 'General Microscopy' },
    'HC': { description: 'Hard Copy' },
    'HD': { description: 'Hemodynamic Waveform' },
    'IO': { description: 'Intra-Oral Radiography' },
    'IOL': { description: 'Intraocular Lens Data' },
    'IVOCT': { description: 'Intravascular Optical Coherence Tomography' },
    'IVUS': { description: 'Intravascular Ultrasound' },
    'KER': { description: 'Keratometry' },
    'KO': { description: 'Key Object Selection' },
    'LEN': { description: 'Lensometry' },
    'LP': { description: 'Laparoscopy', isRetired: true },
    'LS': { description: 'Laser surface scan' },
    'MA': { description: 'Magnetic resonance angiography', isRetired: true },
    'MG': { description: 'Mammography' },
    'MR': { description: 'Magnetic Resonance' },
    'MS': { description: 'Magnetic resonance spectroscopy', isRetired: true },
    'NM': { description: 'Nuclear Medicine' },
    'OAM': { description: 'Ophthalmic Axial Measurements' },
    'OCT': { description: 'Optical Coherence Tomography (non-Ophthalmic)' },
    'OP': { description: 'Ophthalmic Photography' },
    'OPM': { description: 'Ophthalmic Mapping' },
    'OPR': { description: 'Ophthalmic Refraction', isRetired: true },
    'OPT': { description: 'Ophthalmic Tomography' },
    'OPV': { description: 'Ophthalmic Visual Field' },
    'OSS': { description: 'Optical Surface Scan' },
    'OT': { description: 'Other' },
    'PLAN': { description: 'Plan' },
    'PR': { description: 'Presentation State' },
    'PT': { description: 'Positron emission tomography (PET)' },
    'PX': { description: 'Panoramic X-Ray' },
    'REG': { description: 'Registration' },
    'RESP': { description: 'Respiratory Waveform' },
    'RF': { description: 'Radio Fluoroscopy' },
    'RG': { description: 'Radiographic imaging (conventional film/screen)' },
    'RTDOSE': { description: 'Radiotherapy Dose' },
    'RTIMAGE': { description: 'Radiotherapy Image' },
    'RTPLAN': { description: 'Radiotherapy Plan' },
    'RTRECORD': { description: 'RT Treatment Record' },
    'RTSTRUCT': { description: 'Radiotherapy Structure Set' },
    'RWV': { description: 'Real World Value Map' },
    'SEG': { description: 'Segmentation' },
    'SM': { description: 'Slide Microscopy' },
    'SMR': { description: 'Stereometric Relationship' },
    'SR': { description: 'SR Document' },
    'SRF': { description: 'Subjective Refraction' },
    'ST': { description: 'Single-photon emission computed tomography (SPECT)', isRetired: true },
    'STAIN': { description: 'Automated Slide Stainer' },
    'TG': { description: 'Thermography' },
    'US': { description: 'Ultrasound' },
    'VA': { description: 'Visual Acuity' },
    'VF': { description: 'Videofluorography', isRetired: true },
    'XA': { description: 'X-Ray Angiography' },
    'XC': { description: 'External-camera Photography' }
};